config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bikes do
  	resources :booked_days	
  	resources :comments, except: [:show, :index]
  	resources :reservations, except: [:show, :index]
  end
  
  root 'bikes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end

  end
end

app/models/bike.rb
class Bike < ActiveRecord::Base
	belongs_to :category
	has_many :comments
	has_many :reservations
  has_many :booked_days
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", small: "150x150>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	belongs_to :user

	def booked_for?(day)
    contained_in = false

    booked_days.each do |bd|
      if bd.date == day
        contained_in = true
      end
    end
    contained_in
  end



end

app/models/booked_day.rb
class BookedDay < ActiveRecord::Base
	belongs_to :bike
	belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :bikes
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :bike
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :bike
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bikes
  has_many :comments, dependent: :destroy
  has_many :reservations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
	  before_action :find_bike, only: [:show, :edit, :update, :destroy]
	  before_action :authenticate_user!, except: [:index, :show]
	  helper_method :set_average_rating

	def set_average_rating(bike)
		if bike.comments.count == 0
			@avg_rating = 0
	    else
			@avg_rating = bike.comments.average(:rating)
	    end
	    @avg_rating
	end

	def index
		if params[:category].blank?
			@bikes = Bike.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@bikes = Bike.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
		@comments = Comment.where(bike_id: @bike.id).order("created_at DESC")
		@avg_rating = set_average_rating( @bike )
		@date = params[:date] ? Date.parse(params[:date]) : Date.today
	end

	def new
		@bike = current_user.bikes.build
	end

	def create
		@bike = current_user.bikes.build(bikes_params)
		if @bike.save
			redirect_to @bike
		else
			render 'new'
		end
	end


	def availability
		@availability = Availability.new(params[:availability])
		if @availability.save
			redirect_to @bike
		else
			render 'new'
		end

	end

	def update
		if @bike.update(bikes_params)
			redirect_to @bike
		else
			render 'edit'
		end
	end

	def destroy
		@bike.destroy
		redirect_to root_path
	end

	private

	def bikes_params
		params.require(:bike).permit(:category, :title, :image, :description, :url, :start_date, :end_date, :price, :category_id)
	end

	def find_bike
		@bike = Bike.find(params[:id])
	end

	
end

app/controllers/booked_days_controller.rb
class BookedDaysController < ApplicationController
	before_action :find_booked_day, only: [:show, :edit, :update, :destroy]
	  before_action :authenticate_user!
	def new
    @bike = Bike.find(params[:bike_id])
    @booked_day = @bike.booked_days.build
  end

	def create
    @bike = Bike.find(params[:bike_id])
    @booked_day = @bike.booked_days.build booked_day_params
    # binding.pry
    if @booked_day.save
      redirect_to bike_path(@bike)
    else
      render 'new'
    end
	end
	
  def edit
  end

  def update
    @booked_day.update(booked_day_params)
    redirect_to bike_path(@bike)
  end

  def destroy
    @booked_day.destroy
    redirect_to bike_path(@bike)
  end

  private

  def find_booked_day
    @booked_day = Booked_day.find(params[:id])
  end

  def booked_day_params
    params.require(:booked_day).permit(:date)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_bike
  before_action :find_comment, only: [:destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def new
    @comment = @bike.comments.build
  end

	def create
		@bike = Bike.find(params[:bike_id])
		@comment = @bike.comments.new(comment_params)
		@comment.bike_id = @bike.id
    @comment.user_id = current_user.id
		if @comment.save
			redirect_to bike_path(@bike)
		else
			render 'new'
		end
	end
	
  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to bike_path(@bike)
  end

  def destroy
    @comment.destroy
    redirect_to bike_path(@bike)
  end

  private
    def set_comment
      @comment = @bike.comments.find(params[:id])
    end

    def set_bike
      @bike = Bike.find(params[:bike_id])
    end

    def find_comment
    @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:rating, :content)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
	def new
    @bike = Bike.find(params[:bike_id])
    @reservation = @bike.reservations.build
  end

	def create
    @bike = Bike.find(params[:bike_id])
    @reservation = @bike.reservations.build reservation_params
    if @reservation.save
      redirect_to bike_path(@bike)
    else
      render 'new'
    end
	end
	
  def edit
  end

  def update
    @reservation.update(reservation_params)
    redirect_to bike_path(@bike)
  end

  def destroy
    @reservation.destroy
    redirect_to bike_path(@bike)
  end

  private

  def find_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/bookeddays_helper.rb
module BookeddaysHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def calendar(bike, date = Date.today, &block)
    Calendar.new(self, bike, date, block).table
  end
  # calendar helper method defined here

  class Calendar < Struct.new(:view, :bike, :date, :callback)
    HEADER = %w[sun mon tues wed thurs fri sat]
    START_DAY = :sunday

    # struct is defining accessors for attributes

    delegate :content_tag, to: :view

    # delegating to view for any helper methods that can be accessed in the calendar

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    # creates html for table

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    # maps days of the week into header row

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    # generates week and renders day cell

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    # captures block passed in through calendar helper method

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes << "booked" if bike.booked_for?(day)
      classes.empty? ? nil : classes.join(" ")
    end

    # CSS classes for styling

    # rails helper methods for defining current day and sorting weeks into 7 days

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/bikes/_form.html.erb
<%= simple_form_for @bike do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }, input_html: { class: "dropdown-toggle" } %>
  <br/>
  
  
	<br/>
	<%= f.file_field :image %>
	<br/>
  <%= f.input :title, label: "The Bike", input_html: { class: "form-control" } %>
  <%= f.input :description, label: "Descripton:", input_html: { class: "form-control" } %>
  <%= f.input :price, label: "Price per hour:", input_html: { class: "form-control" } %>
   <%= f.button :submit %>
  <% end %>
<%= simple_form_for @bike, :url => bikes_path, :html => { :multipart => true } do |f| %>



<% end %>

app/views/bikes/edit.html.erb
<h1>Edit Bike</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/bikes/index.html.erb
<div class="transitions-enabled" id="bikes">
  <% @bikes.each do |bike| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag bike.image.url()), bike %>
      <h2>
        <%= bike.title %>
      </h2>
      <p class="user">
        Submitted by
        <%= bike.user.name %>
      </p>
      <span>
        <i class="fa fa-comments-o"></i>
        <%= bike.comments.count %>
        <div id="starz" class="star-rating" data-score="<%= set_average_rating(bike) %>"></div>
      </span>
    </div>
  <% end %>
</div>

  

app/views/bikes/new.html.erb
<h1>New Bike</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/bikes/show.html.erb
<div id="bike_show">
  <h1>
    <%= @bike.title %>
  </h1>
  <p class="username">
    Shared by
    <%= @bike.user.name %>
    about
    <%= time_ago_in_words(@bike.created_at) %>
  </p>
  <div class="clearfix">
    <div class="post_image_description">
       <%= image_tag @bike.image.url(:large) %>
         <h3 class="bike-price" data-price="<%= @bike.price.gsub("$", "") %>"><%= @bike.price %> per day</h3>
          <div class="description">
            <%= simple_format(@bike.description) %>
        </div>
    </div>

<div class="post_data">
  <em>Average Rating </em>
   <div id="starzshow" class="star-rating" data-score= <%= @avg_rating%>></div><br/>
    <i class="fa fa-comments-o"></i>
      <%= pluralize(@bike.comments.count, "Comment") %>
        <% if @comments.blank? %>
            <p>None yet. Why don't you add one?</p>
              <%= link_to "Write a comment",  new_bike_comment_path(@bike), class: "button" %>
              <% else %>
                <% @comments.each do |comment| %>
              <div class="reviews">
                <div class="star-rating" data-score= <%= comment.rating %>></div>
                <p><%= comment.content %></p>
                <div class="button">
                <%= link_to "Edit Comment", edit_bike_comment_path(@bike, comment)%>
                <%= link_to "Delete Comment", bike_comment_path(@bike, comment), method: :delete, data: { confirm: "Are you sure?" }  %>
                </div>
                <% end %>
                <% end %>
                <%= link_to "Reserve this bike", new_bike_reservation_path(@bike), class: "button" %>
                <%= link_to "Booked days", new_bike_booked_day_path(@bike), class: "button" %>
                <% if @bike.user == current_user %>
                <%= link_to "Edit Bike", edit_bike_path(@bike), class: "button"  %>
                <%= link_to "Remove Bike", bike_path(@bike), method: :delete, data: { confirm: "Are you sure?" }, class: "button"%>
                <% end %>
                <h2 id="month">
                  <%= link_to "<", date: @date.prev_month %>
                  <%= @date.strftime("%B %Y") %>
                  <%= link_to ">", date: @date.next_month %>
                </h2>
                <div id="availability">
                  <%= calendar(@bike) do | date | %>
                  <%= date.day %>
                  <% end %>
    </div>
</div>

app/views/booked_days/_form.html.erb
<div class="col-md-6">
		<h2><%= @bike.title %></h2>
			<%= simple_form_for([@bike, @booked_day]) do |f| %>
			  <%= f.input :date, label: "booked Day", input_html: { type: 'date' }, class: "col-md-6"  %>
			  <%= f.button :submit, class: "button" %>
			<% end %>
		</br>
</div>

<div class="sidewrapper col-md-4">
	<p><input id="bookeddate" class="btn btn-default button" type="button" value="Submit Day" /></p>
</div>

app/views/booked_days/new.html.erb
<%= render 'form' %>

app/views/comments/_form.html.erb
<%= simple_form_for([@bike, @comment]) do |f| %>
  <div class="editable-star-rating"></div>
  <%= f.input :content, label: "Reply to thread" %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comments</h1>

<%= render 'form' %>

<%= link_to 'Back', bike_path(@bike)  %>

app/views/comments/new.html.erb
<h1>new comments</h1>

<%= render 'form' %>

<%= link_to 'Back', bike_path(@bike)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BikeSpike</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"></link>
  <%= csrf_meta_tags %>
</head>
<body class="bikr">
  <header>
          <h2>Bikr</h2>
            </br>
              <ul id="navigate" class="nav navbar-nav">
                <li>
                  <%= link_to "All Bikes", root_path %>
                </li>
                  <% Category.all.each do |category| %>
                <li>
                  <%= link_to category.name, bikes_path(category: category.name) %>
                </li>
                <% end %>
                  <% if user_signed_in? %>
                  <li class="newbike"><%= link_to "Add New Bike", new_bike_path %></li>
                <% else %>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path  %></li>
                <% end %>
                </ul>
        </header>

  <div class="container">
      <%= yield %>
   </div> 
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>

</html>

app/views/reservations/_form.html.erb
<div class="col-md-6">
		<h2><%= @bike.title %></h2>
			<h3 class="bike-price" data-price="<%= @bike.price.gsub("$", "") %>"><%= @bike.price %> per day</h3>
			<%= simple_form_for([@bike, @reservation]) do |f| %>
			  <%= f.input :start_date, label: "Start date", input_html: { type: 'date' }, class: "col-md-6"  %>
			  <%= f.input :end_date, label: "End date", input_html: { type: 'date' }  %>
			  <%= f.button :submit, class: "button" %>
			<% end %>
		</br>
	<h3>Total cost: <span id="priceObject"></span></h3>
</div>

<div class="sidewrapper col-md-4">
	<p><input id="startbutton" class="btn btn-default button" type="button" value="Submit start" /></p>
	<p><input id="endbutton" class="btn btn-default button" type="button" value="Submit end" /></p>
</div>

app/views/reservations/new.html.erb
<%= render 'form' %>